util.AddNetworkString("HRP_Loaded")
util.AddNetworkString("HRP_RpName")
util.AddNetworkString("HRP_New")
util.AddNetworkString("HRP_EnableMouse")
util.AddNetworkString("HRP_OpenF4Menu")
util.AddNetworkString("HRP_F4MenuJobTable")
util.AddNetworkString("HRP_F4MenuSetJob")