util.AddNetworkString("TRP_Loaded")
util.AddNetworkString("TRP_RpName")
util.AddNetworkString("TRP_New")
util.AddNetworkString("TRP_EnableMouse")
util.AddNetworkString("TRP_F4Menu")
util.AddNetworkString("TRP_F4MenuSetJob")