hook.Add("HRP_SavePlayerData", "HRP_CacheSkills", function (f, ply)
    f:WriteByte(ply:GetNWInt("strength"))
    f:WriteByte(ply:GetNWInt("perception"))
    f:WriteByte(ply:GetNWInt("endurance"))
    f:WriteByte(ply:GetNWInt("charisma"))
    f:WriteByte(ply:GetNWInt("intelligence"))
    f:WriteByte(ply:GetNWInt("agility"))
    f:WriteByte(ply:GetNWInt("luck"))
end)

hook.Add("HRP_LoadPlayerData", "HRP_CacheSkills", function (f, ply)
    ply:SetNWInt("strength", f:ReadByte())
    ply:SetNWInt("perception", f:ReadByte())
    ply:SetNWInt("endurance", f:ReadByte())
    ply:SetNWInt("charisma", f:ReadByte())
    ply:SetNWInt("intelligence", f:ReadByte())
    ply:SetNWInt("agility", f:ReadByte())
    ply:SetNWInt("luck", f:ReadByte())
end)

hook.Add("HRP_InitPlayerData", "HRP_InitSkills", function (ply)
    ply:SetNWInt("strength", 0)
    ply:SetNWInt("perception", 0)
    ply:SetNWInt("endurance", 0)
    ply:SetNWInt("charisma", 0)
    ply:SetNWInt("intelligence", 0)
    ply:SetNWInt("agility", 0)
    ply:SetNWInt("luck", 0)
end)